// Pruebas de firestore.rules: npx firebase emulators:exec --only firestore "node test/reglas.test.mjs"
// (requiere @firebase/rules-unit-testing y firebase instalados)
import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';
import {doc,getDoc,setDoc,updateDoc,deleteDoc,writeBatch} from 'firebase/firestore';
import fs from 'fs';import crypto from 'crypto';
const sha=t=>crypto.createHash('sha256').update(t).digest('hex');
const env=await initializeTestEnvironment({projectId:'poker-rotativo',firestore:{rules:fs.readFileSync(new URL('../firestore.rules',import.meta.url),'utf8'),host:'127.0.0.1',port:8085}});
await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();
  for(const id of ['pA','pB','pmuhuxmb6f8rh']) await setDoc(doc(d,'players',id),{name:id,active:true});
  await setDoc(doc(d,'games','g'),{type:'vie',status:'open',parts:{pA:{st:'juega'},pB:{st:'juega',rb:1}},timer:{running:false,level:0},result:{}});
});
const anon=uid=>env.authenticatedContext(uid,{firebase:{sign_in_provider:'anonymous'}}).firestore();
const google=(uid,email)=>env.authenticatedContext(uid,{email,email_verified:true}).firestore();
const nobody=env.unauthenticatedContext().firestore();
let ok=0,bad=0;const t=async(name,p,expect)=>{try{await (expect?assertSucceeds(p):assertFails(p));ok++;console.log('✓',name)}catch(e){bad++;console.log('✗',name,e.message.slice(0,160))}};
const A=anon('uA'),B=anon('uB'),X=anon('uX'),F=anon('uF'),G=google('uG','claudia@rodo.es'),O=google('uO','otro@gmail.com');
const newPin=(db,pid,pin)=>{const b=writeBatch(db);b.set(doc(db,'pins',pid),{h:sha(pid+':'+pin)});b.set(doc(db,'pinflags',pid),{at:1});return b.commit()};
await t('sin sesión no lee',getDoc(doc(nobody,'players','pA')),false);
await t('anónimo lee jugadores',getDoc(doc(A,'players','pA')),true);
await t('A crea su PIN',newPin(A,'pA','1234'),true);
await t('nadie puede pisar el PIN de A',newPin(X,'pA','9999'),false);
await t('PIN para jugador inexistente',newPin(X,'nadie','1111'),false);
await t('nadie lee el hash',getDoc(doc(X,'pins','pA')),false);
await t('se ve el candado',getDoc(doc(X,'pinflags','pA')),true);
await t('sesión con PIN incorrecto',setDoc(doc(X,'sessions','uX'),{pid:'pA',h:sha('pA:0000')}),false);
await t('sesión con PIN correcto',setDoc(doc(A,'sessions','uA'),{pid:'pA',h:sha('pA:1234')}),true);
await t('no puede crear sesión de otro uid',setDoc(doc(X,'sessions','uA'),{pid:'pA',h:sha('pA:1234')}),false);
await t('A cambia su asistencia',updateDoc(doc(A,'games','g'),{'parts.pA.st':'come',_p:'pA'}),true);
await t('A NO cambia la de B',updateDoc(doc(A,'games','g'),{'parts.pB.st':'no',_p:'pB'}),false);
await t('A suma rebuy a B (partida la maneja cualquiera)',updateDoc(doc(A,'games','g'),{'parts.pB.rb':2,_p:'pB'}),true);
await t('sin PIN no cambia asistencia',updateDoc(doc(X,'games','g'),{'parts.pA.st':'no',_p:'pA'}),false);
await t('sin PIN maneja reloj',updateDoc(doc(X,'games','g'),{'timer.running':true,'timer.level':1}),true);
await t('sin PIN elimina a B',updateDoc(doc(X,'games','g'),{'parts.pB.ko':123,'result.p1':'',_p:'pB'}),true);
await t('no toca dos jugadores a la vez',updateDoc(doc(X,'games','g'),{'parts.pA.rb':1,'parts.pB.rb':3,_p:'pA'}),false);
await t('crear partida vacía',setDoc(doc(X,'games','g2'),{type:'mie',status:'open',parts:{},result:{}}),true);
await t('crear partida con anotados',setDoc(doc(X,'games','g3'),{type:'mie',status:'open',parts:{pB:{st:'no'}}}),false);
await t('anónimo no borra partidas',deleteDoc(doc(X,'games','g2')),false);
await t('anónimo edita jugador',updateDoc(doc(X,'players','pB'),{hand:'K9'}),true);
await t('anónimo no borra jugador',deleteDoc(doc(X,'players','pB')),false);
await t('anónimo no resetea PIN',deleteDoc(doc(X,'pins','pA')),false);
await t('Firu crea su PIN',newPin(F,'pmuhuxmb6f8rh','4321'),true);
await t('Firu entra',setDoc(doc(F,'sessions','uF'),{pid:'pmuhuxmb6f8rh',h:sha('pmuhuxmb6f8rh:4321')}),true);
await t('Firu cambia asistencia de B',updateDoc(doc(F,'games','g'),{'parts.pB.st':'no',_p:'pB'}),true);
await t('Firu borra partida',deleteDoc(doc(F,'games','g2')),true);
await t('Google claudia@rodo.es cambia asistencia de A',updateDoc(doc(G,'games','g'),{'parts.pA.st':'juega',_p:'pA'}),true);
await t('Google otro mail no es admin',updateDoc(doc(O,'games','g'),{'parts.pA.st':'no',_p:'pA'}),false);
await t('Google claudia agrega admin',setDoc(doc(G,'config','admins'),{emails:['otro@gmail.com'],pids:[]}),true);
await t('otro@gmail.com ahora es admin',updateDoc(doc(O,'games','g'),{'parts.pA.st':'no',_p:'pA'}),true);
await t('anónimo no toca admins',setDoc(doc(X,'config','admins'),{emails:['x@x.com']}),false);
await t('A (no organizador) no ve regalos',getDoc(doc(A,'regalos','x')),false);
await t('anónimo no escribe regalos',setDoc(doc(X,'regalos','x'),{monto:1}),false);
await t('Firu escribe regalos',setDoc(doc(F,'regalos','x'),{monto:1000,parts:{}}),true);
await t('Firu lee regalos',getDoc(doc(F,'regalos','x')),true);
await t('Google claudia lee regalos',getDoc(doc(G,'regalos','x')),true);
await t('Google otro admin NO lee regalos',getDoc(doc(O,'regalos','x')),false);
await t('Firu resetea PIN de A',(async()=>{const b=writeBatch(F);b.delete(doc(F,'pins','pA'));b.delete(doc(F,'pinflags','pA'));await b.commit()})(),true);
await t('A con PIN reseteado ya no cambia asistencia',updateDoc(doc(A,'games','g'),{'parts.pA.st':'come',_p:'pA'}),false);
await t('B crea PIN nuevo para A tras el reset',newPin(B,'pA','5555'),true);
await t('A miente en _p para cambiar a B',updateDoc(doc(A,'games','g'),{'parts.pB.st':'come',_p:'pA'}),false);
await t('en partida cerrada un jugador...',(async()=>{await env.withSecurityRulesDisabled(async c=>updateDoc(doc(c.firestore(),'games','g'),{status:'closed'}))})(),true);
console.log(`\n${ok} ok, ${bad} fallaron`);await env.cleanup();process.exit(bad?1:0);
